### ISSUE TITLE
Ability to import from ietf-ribose/bibxml-data-w3c

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-indexer#14]

**Comment by strogonoff** [comment]
Blocked: https://github.com/ietf-ribose/bibxml-data-w3c is empty.

**Comment by strogonoff** [comment]
Blocked: https://github.com/ietf-ribose/bibxml-data-w3c is empty.

**Comment by ronaldtse** [comment]
https://github.com/ietf-ribose/bibxml-data-w3c/issues/1

This is now done.

**Comment by strogonoff** [comment]
Well, our generic implementation is confirmed to work for W3C, so I’m closing this:

http://34.229.41.119:8000/w3c/
http://34.229.41.119:8000/w3c/WD-SWBP-SKOS-CORE-GUIDE-20051102/
http://34.229.41.119:8000/public/rfc/bibxml4/reference.WD-SWBP-SKOS-CORE-GUIDE-20051102.xml

And management UI (auth-protected): http://34.229.41.119:8001/w3c/
