### ISSUE TITLE
Default branch confusion

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-indexer#26]
- If GitHub shows `main` branch when the Code tab is opened, don’t let that confuse you.

- This repository has default branch set to `master`.

- `master` currently has the latest version.

- Important: we must not switch default branch to `main` and delete `master`, because `master` is current.

- We _could_ delete `main` first, then rename `master` to `main`, and then set `main` as default branch.

**Comment by ronaldtse** [comment]
I'll do this.

**Comment by ronaldtse** [comment]
Done
